### PR TITLE
ports/mimxrt: Add rtc alarm/wakeup functionality.

### PR DESCRIPTION
**Pull request by kwagyeman**
Not sure how adding to the main should be handled. Submitting this PR to show that add to main.c.

You should be free to start merging micropython into main.

### CODE REVIEW

**Comment by iabdalkader** [comment]
You should send the PR to our branch not the master, can't merge this.

**Comment by iabdalkader** [comment]
Sorry was looking at the wrong repo, but this also includes changes to the submodule which I have an open PR for here: https://github.com/openmv/openmv/pull/1901

**Comment by kwagyeman** [comment]
Will remove the submodule changes.

**Comment by kwagyeman** [comment]
Updated. This can't be merged until the RTC module is added.

**Comment by iabdalkader** [comment]
I cherry picked this in #1901

**Pull request closed without merging**
