### PR TITLE
examples/ServoShield: Change to SoftI2c for RT.

### PR DESCRIPTION
**Pull request by kidswong999**
Use SoftI2C to support OpenMV RT.

### CODE REVIEW

**Comment by iabdalkader** [comment]
This should also work on the RT1062.

**Comment by kwagyeman** [comment]
@kidswong999 - Any updates on this PR?

**Comment by iabdalkader** [comment]
Can you provide some more details about why this is needed ?

**Comment by kwagyeman** [comment]
@iabdalkader - Verified this pull request fixes an issue with I2C. I2C() requires an ID to be passed.

`I2C(1)`

Works without the keywords. But, will not necessarily match on the STM32 boards.

**Pull request merged**
