### PR TITLE
scripts/examples: Fix typo in MAVLink Apriltag example.

### PR DESCRIPTION
**Pull request by shiv-tyagi**
I apologize for this little bug which was introduced in #1716.  I tested the script before submitting PR #1716 and it was all working fine. But then I discovered this bug while reading the code today. The script would work fine even without this fix but it is still very important to fix it.
Again, sorry for mistakenly introducing this one in that PR. Looking forward to getting it merged soon :)

### CODE REVIEW

**Comment by iabdalkader** [comment]
It's okay, but I can't fix the commit message this time, you have to amend commit message, use:

scripts/examples: Fix typo in MAVLink Apriltag example.

**Comment by shiv-tyagi** [comment]
@iabdalkader Done! Thanks for letting me know the correct commit message format.

**Comment by iabdalkader** [comment]
@shiv-tyagi It also must end with a "." :) 

See some examples here: 

https://github.com/openmv/openmv#contribution-guidelines

This gets parsed later into a change log, so it has to match that pattern.

**Comment by shiv-tyagi** [comment]
@iabdalkader Oops! I have fixed it. Please check if we can merge it now.

**Comment by iabdalkader** [comment]
Merged, thanks!

**Pull request merged**
