### PR TITLE
Add chinese readme

### PR DESCRIPTION
**Pull request by rmokerone**
Modified the README syntax error, and added the Chinese translation.

### CODE REVIEW

**Comment by iabdalkader** [comment]
Hi,

Thanks for the PR, what's oopy.org and why do you add it to our readme ?

**Comment by rmokerone** [comment]
oopy.org is an open source hardware organization in China. We add this URL in this document, only to illustrate that this document is translated(翻译) by the oopy organization:-D

**Comment by iabdalkader** [comment]
I'm sorry but we can't reference an organization which we're not affiliated with, plus the README is really outdated, I'm going to update it in the following days, if you would like to translate the new one without references you're welcome.

**Comment by rmokerone** [comment]
I am very happy to contribute to this project.I did not notice the issue of the organization. If there is a mistake, please forgive me.Thanks again.

**Pull request closed without merging**
