### PR TITLE
imlib: Add scaling and centering hints to draw_image.

### PR DESCRIPTION
**Pull request by kwagyeman**
The SCALE_TO_FIT hint scales the image like keepAspectRatio below but also centers the image. SCALE_TO_FIT_BY_EXPANDING works like keepAspectRatioByExpanding below and also centers the image.
image

### CODE REVIEW

**Comment by kwagyeman** [comment]
Portenta is failing because it's out of flash space...

**Comment by iabdalkader** [comment]
> Portenta is failing because it's out of flash space... Let me know what you want to do.
@kwagyeman 

We can disable OV5640 ? The registers and embedded firmware, AF stuff, take a lot of data. Or just pick a feature to disable.

**Comment by kwagyeman** [comment]
Updated

**Comment by iabdalkader** [comment]
I tested this, works great.

**Pull request merged**
