### PR TITLE
imlib: Move draw_image arguments to struct.

### PR DESCRIPTION
**Pull request by kwagyeman**
Resolves https://github.com/openmv/openmv/issues/1933.

### CODE REVIEW

**Comment by iabdalkader** [comment]
This is good, almost mergable right away, however I have 2 comments:

```suggestion
```

1- I don't think there's a need for a new type `point_rectangle_t`, please reuse the existing ones, you can just pass two `point_t`, `p0`, `p1` to `imlib_draw_image_rectangle`.

2- Speaking of `imlib_draw_image_rectangle`, I think it should be called `imlib_draw_image_get_bounds` or something like that, that function has always confused me, sounds like it's drawing a rectangle but it's not. Also, may want to return the fact that there's nothing to draw `black` using one of the args, whatever works, like setting `x0` to -1 or something.

**Comment by kwagyeman** [comment]
Done!

**Comment by kwagyeman** [comment]
Git rebase interactive appears to have merged two of my commits...

**Comment by kwagyeman** [comment]
Recent changes have not been tested. Will retest if idea is approved.

**Comment by kwagyeman** [comment]
@iabdalkader - This PR is updated as you wanted it.

**Review by iabdalkader — APPROVED** [review]

**Pull request merged**
