### PR TITLE
Add support for April Tag TAG36H8 (#802)

### PR DESCRIPTION
**Pull request by KBacsa**
As far as I know, this fails on the Sipeed MAix BiT for RISC-V.

### CODE REVIEW

**Comment by iabdalkader** [comment]
There's not enough flash to merge this.

**Comment by kwagyeman** [comment]
What is in AprilTag.c? How many tags did you add? 36,000+?

The algorithm will search that table linearly about 16 times in a row trying to match a tag. It's probably too large. You should reduced the number of tags in that family.

**Comment by KBacsa** [comment]
I would like to add a family that would have at least 10,000+ tags. The choices are either adding a 7x7 tag or reducing the hamming distance for 6x6 tags. Is there a smarter way of doing this, or are AprilTags simply not designed for a higher number of detections ?

**Comment by kwagyeman** [comment]
The original code allocates a O(1) lookup table by mallocing 30 MBs+ of memory and then computing each possible tag variant with 1 and 2 bit hamming code errors.

I removed that and used a linear table search instead as 30MB would not fit within the 384 KB of RAM on the M7 when I ported the code.

If you want to do a large number of tags it's possible. However, the algorithm will need to be modified to allow a tag library to be loaded into memory.

The original AprilTag code worked this way so it wouldn't be that difficult to handle. We could add a parameter that lets you pass a tag family. Then, it could internally malloc that tag family with a large lookup table.

However, the O(1) thing burns a ton of ram. A 10K tag family will require probably hundreds of Megabytes of RAM. So, the best you could do would be a linear search... But, that will be very slow.

Just to give you a RAM usage amount... The O(1) table has to make a code per possible bit error per tag for the number of but errors you want. So, with 36-bit tags that's 36 possible variants per tag. With 2 bit errors it's 36 * 36 possible tags per tag.

**Pull request closed without merging**
