### PR TITLE
scripts/rpc.py: Updated to use machine.SPI for rpc_spi_master.

### PR DESCRIPTION
**Pull request by TheSoupMasta**
Changed dependency from pyb to machine.

Note: Couldn't update the slave class because machine doesn't support SPI slaving. Someone will also need to update the arduino library to add slave support for SPI.

### CODE REVIEW

**Comment by TheSoupMasta** [comment]
Will openmv ever create another library similar to pyb that handles the lost features from pyb?

**Comment by kwagyeman** [comment]
@TheSoupMasta - Thanks for the PR. I was going to make the changes today or tomorrow so it works on both. I'll rebase your PR with my changes and get this fix merged.

Regarding the lost features. It's simply a priority thing. There's an infinite amount of work todo and just me an Ibrahim right now. So, for these peripheral features it's always going to be a thing where users have to step up. That said, because the code is open-source and easy to build you can at least do this.

**Comment by TheSoupMasta** [comment]
> @TheSoupMasta - Thanks for the PR. I was going to make the changes today or tomorrow so it works on both. I'll rebase your PR with my changes and get this fix merged.
> 
> Regarding the lost features, it's simply a priority. There's an infinite amount of work to do, and it's just me and Ibrahim right now. So, for these peripheral features, users have to step up. That said, because the code is open-source and easy to build, you can at least do this.
> 
> Note that the lack of SPI slave, I2C Slave, and an official CAN driver (I made one for the RT1062 but it's not official) is from upstream micropython.

Thanks for doing this. I do understand if it is quite difficult for two people to maintain everything so I'm glad that the users can help. Thanks for this.

**Comment by kwagyeman** [comment]
Replaced by: https://github.com/openmv/openmv/pull/2281

@TheSoupMasta - Thank you for PR. I noticed some mistakes in it that would have broken stuff. But, thank you for stepping up and doing it anyway. I've verified support for master mode on the RT1062 for I2C and SPI now.

**Pull request closed without merging**
