### PR TITLE
Apriltag higher res

### PR DESCRIPTION
**Pull request by kwagyeman**

### CODE REVIEW

**Comment by iabdalkader** [comment]
merged.

**Comment by kwagyeman** [comment]
The IDE has an AprilTag generator that can make all the supported tags.

**Comment by binbinshare** [comment]
Can I  design a tag with my own characteristics，not use the library tags.

**Comment by kwagyeman** [comment]
Yes, but, you'll need to edit the firmware to accept the tag family. This is involved...

**Comment by binbinshare** [comment]
Do you have any detailed explanations of the source code about apriltag?I want to know how to deal with it.

**Comment by iabdalkader** [comment]
@binbinshare https://april.eecs.umich.edu/software/apriltag

**Pull request closed without merging**
