### PR TITLE
boards/OPENMV_RT1060: Fix blinking LED polarity.

### PR DESCRIPTION
**Pull request by kwagyeman**

### CODE REVIEW

**Comment by iabdalkader** [comment]
That's not going to fix the inverted polarity, you need to invert this:

https://github.com/openmv/micropython/blob/openmv-1.20/ports/mimxrt/boards/OPENMV_RT1060/mpconfigboard.h#L28

**Comment by iabdalkader** [comment]
I fixed.

**Comment by iabdalkader** [comment]
Ah I see the issue, this is a Pin object not and LED object, will revert the change. However, that code could use an LED object not sure why I used a Pin.

**Comment by kwagyeman** [comment]
So, change this to a LED object?

**Comment by iabdalkader** [comment]
Does this still work using LED object ? Note you'll need to erase the flash to make sure.

**Comment by kwagyeman** [comment]
Yep! I tested it.

**Pull request merged**
