### PR TITLE
Add disable_fb.

### PR DESCRIPTION
**Pull request by kwagyeman**
Allow user control to disable the frame buffer. Necessary for high manual
jpeg image streaming.

### CODE REVIEW

**Comment by iabdalkader** [comment]
1) Do you need to disable all the streaming or just the encode_for_ide part ?
2) I don't see where disable_fb gets reset, if you do a soft-reset it will remain disabled.
3) Can you use fb_ prefix ? It's like new module now.

**Comment by kwagyeman** [comment]
1. Probably should disable all streaming just to make it consistent - only need to disable the encode for IDE part however.
2. Good catch.
3. Prefix on what?

**Comment by iabdalkader** [comment]
> 3. Prefix on what?

To the new functions you just added to framebuffer.c... ex fb_disable_streaming since they're all in framebuffer.c and we may add more later.

**Comment by kwagyeman** [comment]
Updated

**Pull request merged**
