### PR TITLE
modules/py_tf: Revert `load_to_fb` arg name.

### PR DESCRIPTION
**Pull request by iabdalkader**

### CODE REVIEW

**Comment by iabdalkader** [comment]
Would it make sense to rename this to `copy_to_fb` to be consistent with everything else ? @kwagyeman

**Comment by kwagyeman** [comment]
It's not copying an image though, that's why I didn't name it that.

**Comment by iabdalkader** [comment]
> It's not copying an image though, that's why I didn't name it that.

https://docs.openmv.io/library/omv.image.html#image.Image

Loading images with `Image()` doesn't copy either, but it's called `copy_to_fb`.

**Comment by iabdalkader** [comment]
Okay reverted to `load_to_fb`

**Comment by kwagyeman** [comment]
Yes, edge impulse generates scripts with the current naming.

**Pull request merged**
