### PR TITLE
Create pid.py

### PR DESCRIPTION
**Pull request by kidswong999**
refer to https://github.com/SingTown/OpenMV-Pan-Tilt/blob/master/pan-tilt/src/pid.py

### CODE REVIEW

**Comment by kwagyeman** [comment]
Can you add some comments to the script?

**Comment by iabdalkader** [comment]
What does this do ?

**Comment by iabdalkader** [comment]
I want to either merge or close this, any update ?

**Comment by kidswong999** [comment]
I add a small example,
Sorry, I was too busy recently and I forgot about it.😊

**Pull request merged**
