### PR TITLE
imlib/jpegd: Fix jpeg decode for non-multiple of 8.

### PR DESCRIPTION
**Pull request by bitbank2**
This fix corrects the software JPEG decoder when decoding 4:4:4 images and the image size is not a multiple of 8. Previously it would overwrite pixels on the next line or below the last row.

### CODE REVIEW

**Comment by kwagyeman** [comment]
@bitbank2 Please fix your commit message and PR title to be:

"imlib/jpegd: Fix jpeg decode for non-multiple of 8."

**Review by kwagyeman — APPROVED** [review]
I've verified the issue is fixed.

**Comment by iabdalkader** [comment]
I'm waiting for the commit message to be fixed before merging.

**Comment by bitbank2** [comment]
> I'm waiting for the commit message to be fixed before merging.

Which commit message?

**Review by iabdalkader — APPROVED** [review]

**Comment by iabdalkader** [comment]
@bitbank2 Thanks Larry!

> Which commit message?

The commit message which was failing the CI tests, but I see you've already fixed it.

**Comment by bitbank2** [comment]
It's strange because I edited the commit message on github.com, but that didn't seem to make it happen properly.

**Comment by iabdalkader** [comment]
This is just the PR title.

**Pull request merged**
