### PR TITLE
misc: Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S "*.pgm,*.ppm" -L als,dout,extint,hsi,ois,ser,serie`

Note: I found a typo in file title but did not correct. 

`scripts/examples/01-Camera/07-Sensor-Control/sesnor_manual_gain_control.py` should be:
 **sensor**_manual_gain_control.py

I also found typos in `src/hal`, `src/drivers`, `src/omv` but did not add to this PR. Please advise.

### CODE REVIEW

**Comment by iabdalkader** [comment]
> I also found typos in src/hal, src/drivers, src/omv but did not add to this PR. Please advise.

Thank you very much for sending this. `src/hal` and `src/drivers` contain vendor HAL code, and 3rd party drivers (most of them) so shouldn't be fixed, but feel free to fix `src/omv` and send it in a follow-up PR. I also think this check should be added to the code formatting scripts at some point, will see if I can get around to doing that later.

**Comment by luzpaz** [comment]
@iabdalkader what about the file name typo mentioned above ? Fix in follow-up ?

**Comment by iabdalkader** [comment]
> what about the file name typo mentioned above ? Fix in follow-up ?

Sorry I missed that, please fix it in this PR too (using `git mv`).

**Comment by luzpaz** [comment]
> Sorry I missed that, please fix it in this PR too

Done in 213388d

**Review by iabdalkader — APPROVED** [review]

**Pull request merged**
