### PR TITLE
modules/py_image: Update all lineops to use the draw_image backend.

### PR DESCRIPTION
**Pull request by kwagyeman**
Brokeout from https://github.com/openmv/openmv/pull/2061.

This PR switches all lineops over to use draw_image as a backend. This allows all lineops to now work between image types and removes the strict geometry checks. Want to add a scaled and rotated by 90 degrees color jpeg image to a grayscale image? Sure. This works now. You can pretty much do anything with compositing images now. Also, about 5KB code space is saved.

...

Fixes: https://github.com/openmv/openmv/issues/1855

### CODE REVIEW

**Comment by kwagyeman** [comment]
Updated PR and removed imlib_image_operation.

**Comment by iabdalkader** [comment]
Can you please rebase this on master  ?

**Comment by kwagyeman** [comment]
Done

**Comment by iabdalkader** [comment]
I've fixed the broken workflows. If you rebase again it should hopefully work this time.

**Review by iabdalkader — APPROVED** [review]

**Pull request merged**
