### PR TITLE
misc/README: Update builld instructions.

### PR DESCRIPTION
**Pull request by IAmCoder**
I tested the build process on a new machine and needed to add `sudo` - without it there were permission errors.

### CODE REVIEW

**Comment by iabdalkader** [comment]
Actually we need to remove the `sudo` from:
```
sudo mkdir ${TOOLCHAIN_PATH}
```

**Review by iabdalkader — APPROVED** [review]

**Comment by iabdalkader** [comment]
Thanks!

**Comment by iabdalkader** [comment]
I just noticed that `mkdir` is probably missing `-p`.

**Comment by IAmCoder** [comment]
Can add that quick...

**Comment by iabdalkader** [comment]
Go ahead if you like, thanks!

**Pull request merged**
