### PR TITLE
Integration of STM32Cube.AI in the firmware

### PR DESCRIPTION
**Pull request by thibthibaut**
This enables a user to compile a custom version of the OpenMV firmware enabling neural networks generated by [ST tool Cube.AI](https://www.st.com/content/st_com/en/stm32-ann.html).

All the instructions to use Cube.AI with OpenMV are provided in [src/stm32cubeai/Readme.md](https://github.com/thibthibaut/openmv/tree/stm32CubeAI/src/stm32cubeai)

### CODE REVIEW

**Comment by iabdalkader** [comment]
@thibthibaut I think there's a mismatch between the generated code and the libraries in the PR, I'm getting lots of errors when trying to test this with code generated with X-CUBE-AI 4.1.0 ?

`CC data/network.c
data/network.c:231:36: error: macro "AI_TENSOR_OBJ_DECLARE" passed 9 arguments, but takes just 5
   1, &conv2d_3_scratch0_array, NULL)
                                    ^
data/network.c:235:36: error: macro "AI_TENSOR_OBJ_DECLARE" passed 9 arguments, but takes just 5
   1, &conv2d_2_scratch0_array, NULL)
                                    ^
data/network.c:228:1: error: unknown type name 'AI_TENSOR_OBJ_DECLARE'
 AI_TENSOR_OBJ_DECLARE(
`
Which X-CUBE-AI version should I use ?

**Comment by thibthibaut** [comment]
Hello @iabdalkader , you're right I was using the 4.0.0 version of X-Cube-AI hence the missmatch. The latest commit fixes that and supports the 4.1.0 version of the tool.

**Comment by iabdalkader** [comment]
@thibthibaut Thanks for the update. I've merged this PR in #613 and made a few changes to make sure this still works if mpconfigport and qstrs change in the future.

**Comment by thibthibaut** [comment]
Hello Ibrahim,
Thank you for merging the pull request! I added today a little update on
license informations.

Have a nice day!

Thibaut

**Pull request merged**
